service: CF-DynamoDB
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - http:
          path: /api
            method: post
            environment:
            ACCOUNT_ID: 8U29389292
            REGION: us-east-1
